### ISSUE TITLE
Metabug: Track open RTL bugs on Scribus

### ISSUE THREAD

**Issue by luzpaz** [HOST-Oman/scribus#75]
**Tested**
- [x] [2834](https://bugs.scribus.net/view.php?id=2834) "Urdu is displayed Left to Right with Nafees Nastaleeq font"
- [x] [5937](https://bugs.scribus.net/view.php?id=5937) "Lao line wrapping and hyphenization"
- [x] [6004](https://bugs.scribus.net/view.php?id=6004) "wishlist: set default Text Area's content direction to rtl"
- [x] [4452](https://bugs.scribus.net/view.php?id=4452) "No support for Tibetan Script"
- [x] [1364](https://bugs.scribus.net/view.php?id=1364) Hebrew script direction is different in the document and in the story editor
- [x] [1726](https://bugs.scribus.net/view.php?id=1726) "hebrew vowels (and cantillation marks) not placed properly"
- [x] [3680](https://bugs.scribus.net/view.php?id=3680) "Devanagari (Unicode U+09xx) glyph formation (vowels and conjunct consonants) not proper"
- [x] [2920](https://bugs.scribus.net/view.php?id=2920) "Khmer script is rendered wrong"
- [x] [1547](https://bugs.scribus.net/view.php?id=1547) "Support for Indic Scripts"
- [x] [1079](https://bugs.scribus.net/view.php?id=1079) "Arabic is not supported in Scribus yet."
- [x] [6014](https://bugs.scribus.net/view.php?id=6014) "unable to select hebrew text in text area"
- [x] [6013](https://bugs.scribus.net/view.php?id=6013) "hebrew numbers are displaied backwards when text is displaied"
- [x] [6017](https://bugs.scribus.net/view.php?id=6017) "when loading hebrew translation, ui (menus) should be justified to the right"
- [x] [9911](https://bugs.scribus.net/view.php?id=9911) "RL text direction no work"
- [x] [2762](https://bugs.scribus.net/view.php?id=2762) "Unable to set text justification for RTL text"
- [x] [12289](https://bugs.scribus.net/view.php?id=12289) "Diacritics are not positioned correctly in Lao OpenType fonts"
- [x] [11513](https://bugs.scribus.net/view.php?id=11513) "Gujarati Language does not render properly on page"
- [x] [6689](https://bugs.scribus.net/view.php?id=6689) "Parentheses inversion when I'm import hebrew text"
- [x] [6004](https://bugs.scribus.net/view.php?id=6004) "wishlist: set default Text Area's content direction to rtl" (see https://github.com/HOST-Oman/scribus/issues/100)

---

**Untested**

**Comment by Fahad-Alsaidi** [comment]
I have testes most of the bugs and they are fixed in CTL branch. Please spread the word.

**Comment by luzpaz** [comment]
@Fahad-Alsaidi can you test the 'Untested': 6689 "Parentheses inversion when I'm import hebrew text"

**Comment by Fahad-Alsaidi** [comment]
@luzpaz  I have tested and it seems it is fixed but needed test since I can't read Hebrew.
![scribus-multi-langs1](https://cloud.githubusercontent.com/assets/1632566/14042022/87afb964-f28f-11e5-9a4c-b139fc091158.jpg)

**Comment by luzpaz** [comment]
Confirmed. Thanks @Fahad-Alsaidi 
I've added [6004](https://bugs.scribus.net/view.php?id=6004) as well

**Comment by khaledhosny** [comment]
6004 is obsolete, we have a direction in paragraph style and one can just modify the default paragraph style. We just need to make sure we have a way to set it in the styles editor.

**Comment by luzpaz** [comment]
Thanks. I've updated list to reflect that

**Comment by jnahmias** [comment]
Hello, I am fluent (enough) in hebrew and would be happy to test or review any issues.

--Joe

**Comment by Fahad-Alsaidi** [comment]
@jnahmias Thanks, could you confirm above screenshot doesn't have problem in layout?

**Comment by luzpaz** [comment]
Where should I add [6033](https://bugs.scribus.net/view.php?id=6033) ?

**Comment by Fahad-Alsaidi** [comment]
@luzpaz I think [6033](https://bugs.scribus.net/view.php?id=6033) related to [13754](https://bugs.scribus.net/view.php?id=13754).

**Comment by khaledhosny** [comment]
We should now handle line breaking even for scripts that do not use spaces to separate words, but we need someone to confirm it.

**Comment by luzpaz** [comment]
@Fahad-Alsaidi what about https://bugs.scribus.net/view.php?id=9627
is it in the current HOST scope ?

**Comment by Fahad-Alsaidi** [comment]
@luzpaz  [9627](https://bugs.scribus.net/view.php?id=9627) should be fixed but I am waiting the test file.

**Comment by luzpaz** [comment]
RTL UI bugs:
https://bugs.scribus.net/view.php?id=13844

**Comment by jnahmias** [comment]
@Fahad-Alsaidi sorry for the delay, didn't see the notification on this.  The parentheses in the screenshot look correct.

**Comment by khaledhosny** [comment]
Is there anything actionable remaining here?

**Comment by khaledhosny** [comment]
Closing for now, for new issues a new bug should be opened.
