### ISSUE TITLE
Metabug: Track open CJK bugs in Scribus

### ISSUE THREAD

**Issue by luzpaz** [HOST-Oman/scribus#76]
- [ ] [1778](https://bugs.scribus.net/view.php?id=1778) "Support vertical text (Japanese, etc)"
- [ ] [8644](https://bugs.scribus.net/view.php?id=8644) "Double line in one single line in CJK text"
- [ ] [8987](https://bugs.scribus.net/view.php?id=8987) "Word-wrapping CJK fonts malfunction"
- [ ] [7610](https://bugs.scribus.net/view.php?id=7610) "Support for ruby characters (Furigana)"
- [ ] [13612](https://bugs.scribus.net/view.php?id=13612) "No input method preedit when one inputs CJ text directly into a text frame"
- [ ] [9601](https://bugs.scribus.net/view.php?id=9601) "(RFEs) wordwrap problem for Korea (and east Asia)"
- [ ] [13849](https://bugs.scribus.net/view.php?id=13849) "Vertical Script: traditional mongolian/uyghur"
- [ ] [9611](https://bugs.scribus.net/view.php?id=9611) "Font substitute option: mainly needed by Asian/Other Language user as if glyphs missing or ugly"
- [ ] [10322](https://bugs.scribus.net/view.php?id=10322) "Enable the inline editing with input method engine." (related because of impact to CJK)
- [ ] [8655](https://bugs.scribus.net/view.php?id=8655) "Need the use of Double Underline feature with distance adjustment" (reference to Chinese)

**Comment by khaledhosny** [comment]
We need someone to check our CJK line breaking and if it is working properly at all and what bugs are still present.

**Comment by luzpaz** [comment]
@ftake could you do that ?

**Comment by ftake** [comment]
I will do later.

> 8987 "Word-wrapping CJK fonts malfunction"

As far as I know, this has been fixed in 1.5.0 although "box layout" recently broke this again.

**Comment by luzpaz** [comment]
Is [10322](https://bugs.scribus.net/view.php?id=10322) relevant in any way?

**Comment by khaledhosny** [comment]
I think it is, and I think we probably fixed it since most uses of `canRender` is now gone, but we need someone to test it.

**Comment by luzpaz** [comment]
linking to #143
