### ISSUE TITLE
Metabug: Track open 'New Text Layout" bugs in Scribus

### ISSUE THREAD

**Issue by luzpaz** [HOST-Oman/scribus#77]
These bugs are from a [Metabug](https://bugs.scribus.net/view.php?id=2228) in the Scribus BugTracker 
- [ ] [162](https://bugs.scribus.net/view.php?id=162) unequal columns in a textframe
- [ ] [212](https://bugs.scribus.net/view.php?id=212) Ability to create initial vertical space at the beginning of a column
- [ ] [2058](https://bugs.scribus.net/view.php?id=2058) Text and font metrics
- [ ] [1155](https://bugs.scribus.net/view.php?id=1155) Support non-breakable text blocks
- [ ] [1124](https://bugs.scribus.net/view.php?id=1124) Include line-style within paragraph-style, anchor lines in text
- [ ] [1405](https://bugs.scribus.net/view.php?id=1405) Support frame fit adjustment for text
- [ ] [1422](https://bugs.scribus.net/view.php?id=1422) Manual adjustment of word spacing...
- [ ] [1097](https://bugs.scribus.net/view.php?id=1097) Scale frame to text size
- [ ] [2038](https://bugs.scribus.net/view.php?id=2038) extended paragraph styles
- [ ] [1905](https://bugs.scribus.net/view.php?id=1905) separate alignment for last line of paragraph
- [ ] [461](https://bugs.scribus.net/view.php?id=461) drop-cap position for hanging, jutting, etc
- [ ] [204](https://bugs.scribus.net/view.php?id=204) Drop Cap only for the first paragraph
- [ ] [2905](https://bugs.scribus.net/view.php?id=2905) Paragraph styles should have a "keep with next" property.
- [ ] [5481](https://bugs.scribus.net/view.php?id=5481) Number of column defined in text styles
- [ ] [3159](https://bugs.scribus.net/view.php?id=3159) Discretionary hyphenation support
- [ ] [131](https://bugs.scribus.net/view.php?id=131) Ability to have various typographic spacing
- [ ] [2238](https://bugs.scribus.net/view.php?id=2238) Free Text Tool Requested
- [ ] [2495](https://bugs.scribus.net/view.php?id=2495) PDF and PostScript text output one glyph at a time
- [ ] [2542](https://bugs.scribus.net/view.php?id=2542) Formatting Lens
- [ ] [2632](https://bugs.scribus.net/view.php?id=2632) Need to support right side binding in page ordering
- [ ] [1425](https://bugs.scribus.net/view.php?id=1425) Manual kerning dialogue shows automatic FreeType kerning choices...
- [ ] [363](https://bugs.scribus.net/view.php?id=363) differential paragraph styles
- [ ] [2804](https://bugs.scribus.net/view.php?id=2804) Adding Short Cuts for Changing Tracking 
- [x] [4946](https://bugs.scribus.net/view.php?id=4946) Kerning bug
- [ ] [5730](https://bugs.scribus.net/view.php?id=5730) Cursor does not behave correctly in text frame 
- [ ] [9214](https://bugs.scribus.net/view.php?id=9214) Automatic linespacing between paragraphs with different font sizes

---

**Diacritics**
- [x] [13863](https://bugs.scribus.net/view.php?id=13863) combining diacritics not all working
- [x] [8669](https://bugs.scribus.net/view.php?id=8669) IPA diacritics do not position correctly
- [ ] [9365](https://bugs.scribus.net/view.php?id=9365) "The maximum ascent of the capital czech letters with punctuation (??ŽŠ?ÁÍÉ) behaves incorrectly"

**Comment by dawoodalbadi** [comment]
https://bugs.scribus.net/view.php?id=8669 in ctl branch there is no such problem

**Comment by luzpaz** [comment]
https://bugs.scribus.net/view.php?id=9365 "The maximum ascent of the capital czech letters with punctuation (??ŽŠ?ÁÍÉ) behaves incorrectly"

**Comment by luzpaz** [comment]
https://bugs.scribus.net/view.php?id=4686 "text layout should take hyphenation and punctuation into account"

**Comment by Fahad-Alsaidi** [comment]
Most of these bugs are out of scope of HOST unless there is kind of financial support.

**Comment by luzpaz** [comment]
I'm trying to identify which of them are within the current scope of HOST and which are not?

**Comment by khaledhosny** [comment]
Re https://bugs.scribus.net/view.php?id=9365 all that first line offset mess is some Scribus-invented madness AFAIK, and the “Maximum ascent” crap is broken by design. The only fix I see here is to always use “Font ascent” or “Baseline grid” (based on whether a grid is used or not) and drop the other meaningless cases, but this will break old documents. Otherwise it is working as intended (which is to say it is broken by design).
